language: java

jdk:
- oraclejdk8
- oraclejdk9
- openjdk8

install:
- sudo apt-get install -y nmap
- sudo add-apt-repository -y ppa:cpick/hub
- sudo apt-get update
- sudo apt-get install -y hub
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
- mvn test -B

matrix:
 allow_failures:
 - jdk: oraclejdk9

after_success:
- mvn clean test jacoco:report coveralls:report

deploy:
  provider: heroku
  api_key:
   secure: ...
  app: osmartinez-game-of-life
  jdk: openjdk8
  skip_cleanup: true
